language: objective-c
env:
  global:
    - LANG=en_US.UTF-8
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - rake lint
  # - rake docs
