language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
before_script:
  - export LANG=en_US.UTF-8
xcode_workspace: PNChartDemo.xcworkspace
rvm: 2.1.1
